import Link from "next/link";
import { PublicNav } from "@/components/layout/PublicNav";
import { Footer } from "@/components/layout/Footer";
import { QuickSearch } from "@/components/research/QuickSearch";
import { Disclaimer } from "@/components/ui/Disclaimer";
import { ArrowRight, BarChart3, Brain, Globe2, LineChart, MessageCircle, Mail, Shield, Sparkles, Telescope, Zap } from "lucide-react";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-bg text-ink">
      <PublicNav />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 grid-bg opacity-40 pointer-events-none" />
        <div className="absolute inset-0 bg-gradient-to-b from-brand/5 via-transparent to-transparent pointer-events-none" />
        <div className="relative max-w-7xl mx-auto px-4 lg:px-6 pt-16 pb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-brand/30 bg-brand/10 text-brand text-xs">
            <Sparkles className="h-3.5 w-3.5" />
            AI-powered institutional research, made accessible
          </div>
          <h1 className="mt-5 text-4xl md:text-6xl font-semibold tracking-tight text-ink text-balance max-w-4xl">
            Bloomberg-grade equity research on
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand to-brand-600"> any company</span>,
            delivered to your WhatsApp & inbox.
          </h1>
          <p className="mt-5 text-ink-muted text-lg max-w-2xl">
            Kubematrix Financial Research analyzes any listed company across financials, technicals, peers, news, macro and geopolitics — then writes you a hedge-fund-style report.
          </p>
          <div className="mt-7 flex flex-wrap gap-3">
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 rounded-md bg-brand hover:bg-brand-500 text-bg h-12 px-6 font-medium shadow-glow"
            >
              Launch dashboard <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/pricing"
              className="inline-flex items-center gap-2 rounded-md border border-bg-border bg-bg-elevated hover:bg-bg-border text-ink h-12 px-6 font-medium"
            >
              View pricing
            </Link>
          </div>
          <div className="mt-6 flex flex-wrap gap-4 text-xs text-ink-muted">
            <span className="inline-flex items-center gap-1.5"><MessageCircle className="h-3.5 w-3.5 text-bull" /> WhatsApp delivery</span>
            <span className="inline-flex items-center gap-1.5"><Mail className="h-3.5 w-3.5 text-brand" /> Email PDF reports</span>
            <span className="inline-flex items-center gap-1.5"><Shield className="h-3.5 w-3.5 text-caution" /> First report free</span>
          </div>

          <div className="mt-10">
            <QuickSearch />
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-7xl mx-auto px-4 lg:px-6 py-16">
        <div className="text-center max-w-2xl mx-auto">
          <div className="text-xs uppercase tracking-widest text-brand">What you get</div>
          <h2 className="mt-2 text-3xl md:text-4xl font-semibold">A complete research desk in one report</h2>
          <p className="mt-3 text-ink-muted">Every report is generated by our sector-aware AI engine. The output is never generic — content adapts to whether you research a bank, a chip designer or an airline.</p>
        </div>
        <div className="mt-10 grid md:grid-cols-3 gap-4">
          <Feature icon={<Brain className="h-5 w-5" />} title="Sector-aware AI engine" body="Custom templates for semiconductors, banks, airlines, SaaS, pharma, retail, EV, FMCG and energy. Each section adapts to the right metrics, risks and valuation methods." />
          <Feature icon={<BarChart3 className="h-5 w-5" />} title="Institutional report layout" body="Executive summary, thesis, financial & margin analysis, valuation, peer benchmarking, technicals, scenarios, and final recommendation." />
          <Feature icon={<LineChart className="h-5 w-5" />} title="Live-style technical board" body="RSI, MACD, SMAs, EMA, VWAP, Bollinger Bands, ATR, volume trend, support/resistance and a swing-trade setup." />
          <Feature icon={<Globe2 className="h-5 w-5" />} title="Macro & geopolitical lens" body="Tracks the macro indicators that actually drive the stock — rates, crude, FX, commodities, regulation and capex cycles." />
          <Feature icon={<Sparkles className="h-5 w-5" />} title="Investor decision matrix" body="18 institutional scorecards spanning financial health, growth, valuation, sentiment, AI readiness and ESG." />
          <Feature icon={<Zap className="h-5 w-5" />} title="WhatsApp + Email delivery" body="Reports land directly in your WhatsApp and inbox, formatted for desktop and mobile reading." />
        </div>
      </section>

      {/* Sample pricing */}
      <section className="max-w-7xl mx-auto px-4 lg:px-6 pb-16">
        <div className="rounded-2xl border border-bg-border bg-bg-panel/60 p-6 md:p-10 relative overflow-hidden">
          <div className="absolute inset-0 grid-bg opacity-20 pointer-events-none" />
          <div className="relative">
            <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4">
              <div>
                <div className="text-xs uppercase tracking-widest text-brand">Subscription plans</div>
                <h3 className="mt-2 text-2xl md:text-3xl font-semibold">Start free. Scale as your portfolio grows.</h3>
              </div>
              <Link href="/pricing" className="inline-flex items-center gap-2 text-sm text-brand hover:text-brand-400">
                See all plans <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            <div className="mt-6 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
              <PricingTile name="Free" price="₹0" subtitle="1 research report" features={["Any 1 company", "WhatsApp + Email", "Full report PDF"]} />
              <PricingTile name="Starter" price="₹999" subtitle="5 companies" features={["Any 5 companies", "WhatsApp + Email", "Priority support"]} highlight />
              <PricingTile name="Growth" price="₹1,999" subtitle="10 companies" features={["Any 10 companies", "Technical + Macro", "Sector deep-dives"]} />
              <PricingTile name="Pro" price="₹5,999" subtitle="100 companies" features={["Any 100 companies", "Custom watchlist", "Quarterly refresh"]} />
            </div>
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 lg:px-6 pb-16">
        <Disclaimer />
      </section>

      <Footer />
    </div>
  );
}

function Feature({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) {
  return (
    <div className="rounded-xl border border-bg-border bg-bg-card p-5 shadow-card">
      <div className="h-9 w-9 rounded-md bg-brand/15 text-brand inline-flex items-center justify-center">{icon}</div>
      <h3 className="mt-3 text-base font-semibold text-ink">{title}</h3>
      <p className="mt-1.5 text-sm text-ink-muted leading-relaxed">{body}</p>
    </div>
  );
}

function PricingTile({ name, price, subtitle, features, highlight }: { name: string; price: string; subtitle: string; features: string[]; highlight?: boolean }) {
  return (
    <div className={`rounded-xl border p-5 ${highlight ? "border-brand/50 bg-brand/5 shadow-glow" : "border-bg-border bg-bg-card"}`}>
      <div className="flex items-baseline justify-between">
        <div className="text-sm font-semibold text-ink">{name}</div>
        {highlight && <span className="text-[10px] uppercase tracking-widest text-brand">Most popular</span>}
      </div>
      <div className="mt-2 text-2xl font-semibold text-ink tabular-nums">{price}</div>
      <div className="text-xs text-ink-muted">{subtitle}</div>
      <ul className="mt-3 space-y-1 text-xs text-ink-muted">
        {features.map((f) => <li key={f}>• {f}</li>)}
      </ul>
    </div>
  );
}
